blank_issues_enabled: false
contact_links:
  - name: Questions and general support
    url: https://github.com/AuRA-AI/aura-ai/discussions
    about: Please use Discussions for questions and support requests.
